import './globals.css';

export const metadata = {
  title: 'Multer - Unbounce Landing PAge',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
